/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as agentManagerSol from "./AgentManager.sol";
export type { agentManagerSol };
import type * as agentManagerV2Sol from "./AgentManagerV2.sol";
export type { agentManagerV2Sol };
import type * as caLotteryOldSol from "./CALotteryOld.sol";
export type { caLotteryOldSol };
import type * as freeSol from "./Free.sol";
export type { freeSol };
import type * as insurAceAgentSol from "./InsurAceAgent.sol";
export type { insurAceAgentSol };
import type * as randomnumbergeneratorSol from "./Randomnumbergenerator.sol";
export type { randomnumbergeneratorSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { CALottery } from "./CALottery";
export type { Helper } from "./Helper";
export type { Timelock } from "./Timelock";
