/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as agentManagerSol from "./AgentManager.sol";
export type { agentManagerSol };
import type * as autofarmSol from "./Autofarm.sol";
export type { autofarmSol };
import type * as insurAceAgentSol from "./InsurAceAgent.sol";
export type { insurAceAgentSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
