/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as icaLotteryOldSol from "./ICALotteryOld.sol";
export type { icaLotteryOldSol };
export type { IAgent } from "./IAgent";
export type { IAgentManager } from "./IAgentManager";
export type { ICALottery } from "./ICALottery";
export type { IRandomNumberGenerator } from "./IRandomNumberGenerator";
