/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface IRandomNumberGeneratorInterface extends utils.Interface {
  functions: {
    "getRandomNumber(uint256)": FunctionFragment;
    "viewLatestLotteryId()": FunctionFragment;
    "viewRandomResult()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "getRandomNumber"
      | "viewLatestLotteryId"
      | "viewRandomResult"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getRandomNumber",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "viewLatestLotteryId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "viewRandomResult",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getRandomNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "viewLatestLotteryId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "viewRandomResult",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IRandomNumberGenerator extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IRandomNumberGeneratorInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getRandomNumber(
      _seed: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    viewLatestLotteryId(overrides?: CallOverrides): Promise<[BigNumber]>;

    viewRandomResult(overrides?: CallOverrides): Promise<[number]>;
  };

  getRandomNumber(
    _seed: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  viewLatestLotteryId(overrides?: CallOverrides): Promise<BigNumber>;

  viewRandomResult(overrides?: CallOverrides): Promise<number>;

  callStatic: {
    getRandomNumber(
      _seed: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    viewLatestLotteryId(overrides?: CallOverrides): Promise<BigNumber>;

    viewRandomResult(overrides?: CallOverrides): Promise<number>;
  };

  filters: {};

  estimateGas: {
    getRandomNumber(
      _seed: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    viewLatestLotteryId(overrides?: CallOverrides): Promise<BigNumber>;

    viewRandomResult(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getRandomNumber(
      _seed: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    viewLatestLotteryId(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    viewRandomResult(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
