/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ILPToken,
  ILPTokenInterface,
} from "../../../contracts/Ellipsis.sol/ILPToken";

const _abi = [
  {
    inputs: [],
    name: "getReward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ILPToken__factory {
  static readonly abi = _abi;
  static createInterface(): ILPTokenInterface {
    return new utils.Interface(_abi) as ILPTokenInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILPToken {
    return new Contract(address, _abi, signerOrProvider) as ILPToken;
  }
}
