/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface IRewardControllerInterface extends utils.Interface {
  functions: {
    "getRewardInfo()": FunctionFragment;
    "unlockReward(address[],bool,bool,bool)": FunctionFragment;
    "withdrawReward(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "getRewardInfo" | "unlockReward" | "withdrawReward"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getRewardInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "unlockReward",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<boolean>,
      PromiseOrValue<boolean>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawReward",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "getRewardInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawReward",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IRewardController extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IRewardControllerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getRewardInfo(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { r0: BigNumber; r1: BigNumber }>;

    unlockReward(
      _tokenList: PromiseOrValue<string>[],
      _bBuyCoverUnlockedAmt: PromiseOrValue<boolean>,
      _bClaimUnlockedAmt: PromiseOrValue<boolean>,
      _bReferralUnlockedAmt: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawReward(
      _pid: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  getRewardInfo(
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber] & { r0: BigNumber; r1: BigNumber }>;

  unlockReward(
    _tokenList: PromiseOrValue<string>[],
    _bBuyCoverUnlockedAmt: PromiseOrValue<boolean>,
    _bClaimUnlockedAmt: PromiseOrValue<boolean>,
    _bReferralUnlockedAmt: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawReward(
    _pid: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getRewardInfo(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { r0: BigNumber; r1: BigNumber }>;

    unlockReward(
      _tokenList: PromiseOrValue<string>[],
      _bBuyCoverUnlockedAmt: PromiseOrValue<boolean>,
      _bClaimUnlockedAmt: PromiseOrValue<boolean>,
      _bReferralUnlockedAmt: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawReward(
      _pid: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getRewardInfo(overrides?: CallOverrides): Promise<BigNumber>;

    unlockReward(
      _tokenList: PromiseOrValue<string>[],
      _bBuyCoverUnlockedAmt: PromiseOrValue<boolean>,
      _bClaimUnlockedAmt: PromiseOrValue<boolean>,
      _bReferralUnlockedAmt: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawReward(
      _pid: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getRewardInfo(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    unlockReward(
      _tokenList: PromiseOrValue<string>[],
      _bBuyCoverUnlockedAmt: PromiseOrValue<boolean>,
      _bClaimUnlockedAmt: PromiseOrValue<boolean>,
      _bReferralUnlockedAmt: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawReward(
      _pid: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
