/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as icaLotteryOldSol from "./ICALotteryOld.sol";
export { IAgent__factory } from "./IAgent__factory";
export { IAgentManager__factory } from "./IAgentManager__factory";
export { ICALottery__factory } from "./ICALottery__factory";
export { IRandomNumberGenerator__factory } from "./IRandomNumberGenerator__factory";
