/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace CALottery {
  export type LotteryStruct = {
    status: PromiseOrValue<BigNumberish>;
    startTime: PromiseOrValue<BigNumberish>;
    endTime: PromiseOrValue<BigNumberish>;
    priceTicketInBusd: PromiseOrValue<BigNumberish>;
    discountDivisor: PromiseOrValue<BigNumberish>;
    rewardsBreakdown: PromiseOrValue<BigNumberish>[];
    treasuryFee: PromiseOrValue<BigNumberish>;
    busdPerBracket: PromiseOrValue<BigNumberish>[];
    countWinnersPerBracket: PromiseOrValue<BigNumberish>[];
    firstTicketId: PromiseOrValue<BigNumberish>;
    firstTicketIdNextLottery: PromiseOrValue<BigNumberish>;
    amountCollectedInBusd: PromiseOrValue<BigNumberish>;
    finalNumber: PromiseOrValue<BigNumberish>;
  };

  export type LotteryStructOutput = [
    number,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber[],
    BigNumber,
    BigNumber[],
    BigNumber[],
    BigNumber,
    BigNumber,
    BigNumber,
    number
  ] & {
    status: number;
    startTime: BigNumber;
    endTime: BigNumber;
    priceTicketInBusd: BigNumber;
    discountDivisor: BigNumber;
    rewardsBreakdown: BigNumber[];
    treasuryFee: BigNumber;
    busdPerBracket: BigNumber[];
    countWinnersPerBracket: BigNumber[];
    firstTicketId: BigNumber;
    firstTicketIdNextLottery: BigNumber;
    amountCollectedInBusd: BigNumber;
    finalNumber: number;
  };
}

export interface CALotteryInterface extends utils.Interface {
  functions: {
    "MAX_LENGTH_LOTTERY()": FunctionFragment;
    "MAX_TREASURY_FEE()": FunctionFragment;
    "MIN_DISCOUNT_DIVISOR()": FunctionFragment;
    "MIN_LENGTH_LOTTERY()": FunctionFragment;
    "busdToken()": FunctionFragment;
    "buyTickets(uint256,uint32[])": FunctionFragment;
    "calculateTotalPriceForBulkTickets(uint256,uint256,uint256)": FunctionFragment;
    "changeRandomGenerator(address)": FunctionFragment;
    "claimTickets(uint256,uint256[],uint32[])": FunctionFragment;
    "closeLottery(uint256)": FunctionFragment;
    "currentLotteryId()": FunctionFragment;
    "currentTicketId()": FunctionFragment;
    "drawFinalNumberAndMakeLotteryClaimable(uint256,bool)": FunctionFragment;
    "freeToken()": FunctionFragment;
    "injectFunds(uint256,uint256)": FunctionFragment;
    "injectorAddress()": FunctionFragment;
    "manager()": FunctionFragment;
    "maxNumberTicketsPerBuyOrClaim()": FunctionFragment;
    "maxPriceTicketInBusd()": FunctionFragment;
    "minPriceTicketInBusd()": FunctionFragment;
    "operatorAddress()": FunctionFragment;
    "owner()": FunctionFragment;
    "pendingAmountToWinners()": FunctionFragment;
    "pendingInjectionNextLottery()": FunctionFragment;
    "randomGenerator()": FunctionFragment;
    "recoverWrongTokens(address,uint256)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setMaxNumberTicketsPerBuy(uint256)": FunctionFragment;
    "setMinAndMaxTicketPriceInBusd(uint256,uint256)": FunctionFragment;
    "setOperatorAndTreasuryAndInjectorAddresses(address,address,address)": FunctionFragment;
    "startLottery(uint256,uint256,uint256,uint256[6],uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "treasuryAddress()": FunctionFragment;
    "viewCurrentLotteryId()": FunctionFragment;
    "viewLottery(uint256)": FunctionFragment;
    "viewNumbersAndStatusesForTicketIds(uint256[])": FunctionFragment;
    "viewRewardsForTicketId(uint256,uint256,uint32)": FunctionFragment;
    "viewUserInfoForLotteryId(address,uint256,uint256,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "MAX_LENGTH_LOTTERY"
      | "MAX_TREASURY_FEE"
      | "MIN_DISCOUNT_DIVISOR"
      | "MIN_LENGTH_LOTTERY"
      | "busdToken"
      | "buyTickets"
      | "calculateTotalPriceForBulkTickets"
      | "changeRandomGenerator"
      | "claimTickets"
      | "closeLottery"
      | "currentLotteryId"
      | "currentTicketId"
      | "drawFinalNumberAndMakeLotteryClaimable"
      | "freeToken"
      | "injectFunds"
      | "injectorAddress"
      | "manager"
      | "maxNumberTicketsPerBuyOrClaim"
      | "maxPriceTicketInBusd"
      | "minPriceTicketInBusd"
      | "operatorAddress"
      | "owner"
      | "pendingAmountToWinners"
      | "pendingInjectionNextLottery"
      | "randomGenerator"
      | "recoverWrongTokens"
      | "renounceOwnership"
      | "setMaxNumberTicketsPerBuy"
      | "setMinAndMaxTicketPriceInBusd"
      | "setOperatorAndTreasuryAndInjectorAddresses"
      | "startLottery"
      | "transferOwnership"
      | "treasuryAddress"
      | "viewCurrentLotteryId"
      | "viewLottery"
      | "viewNumbersAndStatusesForTicketIds"
      | "viewRewardsForTicketId"
      | "viewUserInfoForLotteryId"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "MAX_LENGTH_LOTTERY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_TREASURY_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_DISCOUNT_DIVISOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_LENGTH_LOTTERY",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "busdToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "buyTickets",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateTotalPriceForBulkTickets",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "changeRandomGenerator",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "claimTickets",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "closeLottery",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "currentLotteryId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentTicketId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "drawFinalNumberAndMakeLotteryClaimable",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(functionFragment: "freeToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "injectFunds",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "injectorAddress",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "manager", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "maxNumberTicketsPerBuyOrClaim",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxPriceTicketInBusd",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minPriceTicketInBusd",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "operatorAddress",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingAmountToWinners",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingInjectionNextLottery",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "randomGenerator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recoverWrongTokens",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxNumberTicketsPerBuy",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinAndMaxTicketPriceInBusd",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setOperatorAndTreasuryAndInjectorAddresses",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "startLottery",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "treasuryAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "viewCurrentLotteryId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "viewLottery",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "viewNumbersAndStatusesForTicketIds",
    values: [PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "viewRewardsForTicketId",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "viewUserInfoForLotteryId",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_LENGTH_LOTTERY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_TREASURY_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_DISCOUNT_DIVISOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_LENGTH_LOTTERY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "busdToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buyTickets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculateTotalPriceForBulkTickets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeRandomGenerator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimTickets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closeLottery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentLotteryId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentTicketId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "drawFinalNumberAndMakeLotteryClaimable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "freeToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "injectFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "injectorAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "manager", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxNumberTicketsPerBuyOrClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxPriceTicketInBusd",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minPriceTicketInBusd",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "operatorAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingAmountToWinners",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingInjectionNextLottery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "randomGenerator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recoverWrongTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxNumberTicketsPerBuy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinAndMaxTicketPriceInBusd",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOperatorAndTreasuryAndInjectorAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startLottery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "treasuryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "viewCurrentLotteryId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "viewLottery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "viewNumbersAndStatusesForTicketIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "viewRewardsForTicketId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "viewUserInfoForLotteryId",
    data: BytesLike
  ): Result;

  events: {
    "AdminTokenRecovery(address,uint256)": EventFragment;
    "LotteryClose(uint256,uint256)": EventFragment;
    "LotteryInjection(uint256,uint256)": EventFragment;
    "LotteryNumberDrawn(uint256,uint256,uint256)": EventFragment;
    "LotteryOpen(uint256,uint256,uint256,uint256,uint256,uint256)": EventFragment;
    "NewOperatorAndTreasuryAndInjectorAddresses(address,address,address)": EventFragment;
    "NewRandomGenerator(address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "TicketsClaim(address,uint256,uint256,uint256)": EventFragment;
    "TicketsPurchase(address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AdminTokenRecovery"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LotteryClose"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LotteryInjection"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LotteryNumberDrawn"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LotteryOpen"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "NewOperatorAndTreasuryAndInjectorAddresses"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewRandomGenerator"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TicketsClaim"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TicketsPurchase"): EventFragment;
}

export interface AdminTokenRecoveryEventObject {
  token: string;
  amount: BigNumber;
}
export type AdminTokenRecoveryEvent = TypedEvent<
  [string, BigNumber],
  AdminTokenRecoveryEventObject
>;

export type AdminTokenRecoveryEventFilter =
  TypedEventFilter<AdminTokenRecoveryEvent>;

export interface LotteryCloseEventObject {
  lotteryId: BigNumber;
  firstTicketIdNextLottery: BigNumber;
}
export type LotteryCloseEvent = TypedEvent<
  [BigNumber, BigNumber],
  LotteryCloseEventObject
>;

export type LotteryCloseEventFilter = TypedEventFilter<LotteryCloseEvent>;

export interface LotteryInjectionEventObject {
  lotteryId: BigNumber;
  injectedAmount: BigNumber;
}
export type LotteryInjectionEvent = TypedEvent<
  [BigNumber, BigNumber],
  LotteryInjectionEventObject
>;

export type LotteryInjectionEventFilter =
  TypedEventFilter<LotteryInjectionEvent>;

export interface LotteryNumberDrawnEventObject {
  lotteryId: BigNumber;
  finalNumber: BigNumber;
  countWinningTickets: BigNumber;
}
export type LotteryNumberDrawnEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber],
  LotteryNumberDrawnEventObject
>;

export type LotteryNumberDrawnEventFilter =
  TypedEventFilter<LotteryNumberDrawnEvent>;

export interface LotteryOpenEventObject {
  lotteryId: BigNumber;
  startTime: BigNumber;
  endTime: BigNumber;
  priceTicketInBusd: BigNumber;
  firstTicketId: BigNumber;
  injectedAmount: BigNumber;
}
export type LotteryOpenEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber],
  LotteryOpenEventObject
>;

export type LotteryOpenEventFilter = TypedEventFilter<LotteryOpenEvent>;

export interface NewOperatorAndTreasuryAndInjectorAddressesEventObject {
  operator: string;
  treasury: string;
  injector: string;
}
export type NewOperatorAndTreasuryAndInjectorAddressesEvent = TypedEvent<
  [string, string, string],
  NewOperatorAndTreasuryAndInjectorAddressesEventObject
>;

export type NewOperatorAndTreasuryAndInjectorAddressesEventFilter =
  TypedEventFilter<NewOperatorAndTreasuryAndInjectorAddressesEvent>;

export interface NewRandomGeneratorEventObject {
  randomGenerator: string;
}
export type NewRandomGeneratorEvent = TypedEvent<
  [string],
  NewRandomGeneratorEventObject
>;

export type NewRandomGeneratorEventFilter =
  TypedEventFilter<NewRandomGeneratorEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface TicketsClaimEventObject {
  claimer: string;
  amount: BigNumber;
  lotteryId: BigNumber;
  numberTickets: BigNumber;
}
export type TicketsClaimEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber],
  TicketsClaimEventObject
>;

export type TicketsClaimEventFilter = TypedEventFilter<TicketsClaimEvent>;

export interface TicketsPurchaseEventObject {
  buyer: string;
  lotteryId: BigNumber;
  numberTickets: BigNumber;
}
export type TicketsPurchaseEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  TicketsPurchaseEventObject
>;

export type TicketsPurchaseEventFilter = TypedEventFilter<TicketsPurchaseEvent>;

export interface CALottery extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CALotteryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    MAX_LENGTH_LOTTERY(overrides?: CallOverrides): Promise<[BigNumber]>;

    MAX_TREASURY_FEE(overrides?: CallOverrides): Promise<[BigNumber]>;

    MIN_DISCOUNT_DIVISOR(overrides?: CallOverrides): Promise<[BigNumber]>;

    MIN_LENGTH_LOTTERY(overrides?: CallOverrides): Promise<[BigNumber]>;

    busdToken(overrides?: CallOverrides): Promise<[string]>;

    buyTickets(
      _lotteryId: PromiseOrValue<BigNumberish>,
      _ticketNumbers: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    calculateTotalPriceForBulkTickets(
      _discountDivisor: PromiseOrValue<BigNumberish>,
      _priceTicket: PromiseOrValue<BigNumberish>,
      _numberTickets: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    changeRandomGenerator(
      _randomGeneratorAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    claimTickets(
      _lotteryId: PromiseOrValue<BigNumberish>,
      _ticketIds: PromiseOrValue<BigNumberish>[],
      _brackets: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    closeLottery(
      _lotteryId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    currentLotteryId(overrides?: CallOverrides): Promise<[BigNumber]>;

    currentTicketId(overrides?: CallOverrides): Promise<[BigNumber]>;

    drawFinalNumberAndMakeLotteryClaimable(
      _lotteryId: PromiseOrValue<BigNumberish>,
      _autoInjection: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    freeToken(overrides?: CallOverrides): Promise<[string]>;

    injectFunds(
      _lotteryId: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    injectorAddress(overrides?: CallOverrides): Promise<[string]>;

    manager(overrides?: CallOverrides): Promise<[string]>;

    maxNumberTicketsPerBuyOrClaim(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    maxPriceTicketInBusd(overrides?: CallOverrides): Promise<[BigNumber]>;

    minPriceTicketInBusd(overrides?: CallOverrides): Promise<[BigNumber]>;

    operatorAddress(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pendingAmountToWinners(overrides?: CallOverrides): Promise<[BigNumber]>;

    pendingInjectionNextLottery(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    randomGenerator(overrides?: CallOverrides): Promise<[string]>;

    recoverWrongTokens(
      _tokenAddress: PromiseOrValue<string>,
      _tokenAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setMaxNumberTicketsPerBuy(
      _maxNumberTicketsPerBuy: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setMinAndMaxTicketPriceInBusd(
      _minPriceTicketInBusd: PromiseOrValue<BigNumberish>,
      _maxPriceTicketInBusd: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setOperatorAndTreasuryAndInjectorAddresses(
      _operatorAddress: PromiseOrValue<string>,
      _treasuryAddress: PromiseOrValue<string>,
      _injectorAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    startLottery(
      _endTime: PromiseOrValue<BigNumberish>,
      _priceTicketInBusd: PromiseOrValue<BigNumberish>,
      _discountDivisor: PromiseOrValue<BigNumberish>,
      _rewardsBreakdown: PromiseOrValue<BigNumberish>[],
      _treasuryFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    treasuryAddress(overrides?: CallOverrides): Promise<[string]>;

    viewCurrentLotteryId(overrides?: CallOverrides): Promise<[BigNumber]>;

    viewLottery(
      _lotteryId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[CALottery.LotteryStructOutput]>;

    viewNumbersAndStatusesForTicketIds(
      _ticketIds: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<[number[], boolean[]]>;

    viewRewardsForTicketId(
      _lotteryId: PromiseOrValue<BigNumberish>,
      _ticketId: PromiseOrValue<BigNumberish>,
      _bracket: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    viewUserInfoForLotteryId(
      _user: PromiseOrValue<string>,
      _lotteryId: PromiseOrValue<BigNumberish>,
      _cursor: PromiseOrValue<BigNumberish>,
      _size: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber[], number[], boolean[], BigNumber]>;
  };

  MAX_LENGTH_LOTTERY(overrides?: CallOverrides): Promise<BigNumber>;

  MAX_TREASURY_FEE(overrides?: CallOverrides): Promise<BigNumber>;

  MIN_DISCOUNT_DIVISOR(overrides?: CallOverrides): Promise<BigNumber>;

  MIN_LENGTH_LOTTERY(overrides?: CallOverrides): Promise<BigNumber>;

  busdToken(overrides?: CallOverrides): Promise<string>;

  buyTickets(
    _lotteryId: PromiseOrValue<BigNumberish>,
    _ticketNumbers: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  calculateTotalPriceForBulkTickets(
    _discountDivisor: PromiseOrValue<BigNumberish>,
    _priceTicket: PromiseOrValue<BigNumberish>,
    _numberTickets: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  changeRandomGenerator(
    _randomGeneratorAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  claimTickets(
    _lotteryId: PromiseOrValue<BigNumberish>,
    _ticketIds: PromiseOrValue<BigNumberish>[],
    _brackets: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  closeLottery(
    _lotteryId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  currentLotteryId(overrides?: CallOverrides): Promise<BigNumber>;

  currentTicketId(overrides?: CallOverrides): Promise<BigNumber>;

  drawFinalNumberAndMakeLotteryClaimable(
    _lotteryId: PromiseOrValue<BigNumberish>,
    _autoInjection: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  freeToken(overrides?: CallOverrides): Promise<string>;

  injectFunds(
    _lotteryId: PromiseOrValue<BigNumberish>,
    _amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  injectorAddress(overrides?: CallOverrides): Promise<string>;

  manager(overrides?: CallOverrides): Promise<string>;

  maxNumberTicketsPerBuyOrClaim(overrides?: CallOverrides): Promise<BigNumber>;

  maxPriceTicketInBusd(overrides?: CallOverrides): Promise<BigNumber>;

  minPriceTicketInBusd(overrides?: CallOverrides): Promise<BigNumber>;

  operatorAddress(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  pendingAmountToWinners(overrides?: CallOverrides): Promise<BigNumber>;

  pendingInjectionNextLottery(overrides?: CallOverrides): Promise<BigNumber>;

  randomGenerator(overrides?: CallOverrides): Promise<string>;

  recoverWrongTokens(
    _tokenAddress: PromiseOrValue<string>,
    _tokenAmount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setMaxNumberTicketsPerBuy(
    _maxNumberTicketsPerBuy: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setMinAndMaxTicketPriceInBusd(
    _minPriceTicketInBusd: PromiseOrValue<BigNumberish>,
    _maxPriceTicketInBusd: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setOperatorAndTreasuryAndInjectorAddresses(
    _operatorAddress: PromiseOrValue<string>,
    _treasuryAddress: PromiseOrValue<string>,
    _injectorAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  startLottery(
    _endTime: PromiseOrValue<BigNumberish>,
    _priceTicketInBusd: PromiseOrValue<BigNumberish>,
    _discountDivisor: PromiseOrValue<BigNumberish>,
    _rewardsBreakdown: PromiseOrValue<BigNumberish>[],
    _treasuryFee: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  treasuryAddress(overrides?: CallOverrides): Promise<string>;

  viewCurrentLotteryId(overrides?: CallOverrides): Promise<BigNumber>;

  viewLottery(
    _lotteryId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<CALottery.LotteryStructOutput>;

  viewNumbersAndStatusesForTicketIds(
    _ticketIds: PromiseOrValue<BigNumberish>[],
    overrides?: CallOverrides
  ): Promise<[number[], boolean[]]>;

  viewRewardsForTicketId(
    _lotteryId: PromiseOrValue<BigNumberish>,
    _ticketId: PromiseOrValue<BigNumberish>,
    _bracket: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  viewUserInfoForLotteryId(
    _user: PromiseOrValue<string>,
    _lotteryId: PromiseOrValue<BigNumberish>,
    _cursor: PromiseOrValue<BigNumberish>,
    _size: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[BigNumber[], number[], boolean[], BigNumber]>;

  callStatic: {
    MAX_LENGTH_LOTTERY(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_TREASURY_FEE(overrides?: CallOverrides): Promise<BigNumber>;

    MIN_DISCOUNT_DIVISOR(overrides?: CallOverrides): Promise<BigNumber>;

    MIN_LENGTH_LOTTERY(overrides?: CallOverrides): Promise<BigNumber>;

    busdToken(overrides?: CallOverrides): Promise<string>;

    buyTickets(
      _lotteryId: PromiseOrValue<BigNumberish>,
      _ticketNumbers: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    calculateTotalPriceForBulkTickets(
      _discountDivisor: PromiseOrValue<BigNumberish>,
      _priceTicket: PromiseOrValue<BigNumberish>,
      _numberTickets: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    changeRandomGenerator(
      _randomGeneratorAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    claimTickets(
      _lotteryId: PromiseOrValue<BigNumberish>,
      _ticketIds: PromiseOrValue<BigNumberish>[],
      _brackets: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    closeLottery(
      _lotteryId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    currentLotteryId(overrides?: CallOverrides): Promise<BigNumber>;

    currentTicketId(overrides?: CallOverrides): Promise<BigNumber>;

    drawFinalNumberAndMakeLotteryClaimable(
      _lotteryId: PromiseOrValue<BigNumberish>,
      _autoInjection: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    freeToken(overrides?: CallOverrides): Promise<string>;

    injectFunds(
      _lotteryId: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    injectorAddress(overrides?: CallOverrides): Promise<string>;

    manager(overrides?: CallOverrides): Promise<string>;

    maxNumberTicketsPerBuyOrClaim(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    maxPriceTicketInBusd(overrides?: CallOverrides): Promise<BigNumber>;

    minPriceTicketInBusd(overrides?: CallOverrides): Promise<BigNumber>;

    operatorAddress(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    pendingAmountToWinners(overrides?: CallOverrides): Promise<BigNumber>;

    pendingInjectionNextLottery(overrides?: CallOverrides): Promise<BigNumber>;

    randomGenerator(overrides?: CallOverrides): Promise<string>;

    recoverWrongTokens(
      _tokenAddress: PromiseOrValue<string>,
      _tokenAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setMaxNumberTicketsPerBuy(
      _maxNumberTicketsPerBuy: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setMinAndMaxTicketPriceInBusd(
      _minPriceTicketInBusd: PromiseOrValue<BigNumberish>,
      _maxPriceTicketInBusd: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setOperatorAndTreasuryAndInjectorAddresses(
      _operatorAddress: PromiseOrValue<string>,
      _treasuryAddress: PromiseOrValue<string>,
      _injectorAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    startLottery(
      _endTime: PromiseOrValue<BigNumberish>,
      _priceTicketInBusd: PromiseOrValue<BigNumberish>,
      _discountDivisor: PromiseOrValue<BigNumberish>,
      _rewardsBreakdown: PromiseOrValue<BigNumberish>[],
      _treasuryFee: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    treasuryAddress(overrides?: CallOverrides): Promise<string>;

    viewCurrentLotteryId(overrides?: CallOverrides): Promise<BigNumber>;

    viewLottery(
      _lotteryId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<CALottery.LotteryStructOutput>;

    viewNumbersAndStatusesForTicketIds(
      _ticketIds: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<[number[], boolean[]]>;

    viewRewardsForTicketId(
      _lotteryId: PromiseOrValue<BigNumberish>,
      _ticketId: PromiseOrValue<BigNumberish>,
      _bracket: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    viewUserInfoForLotteryId(
      _user: PromiseOrValue<string>,
      _lotteryId: PromiseOrValue<BigNumberish>,
      _cursor: PromiseOrValue<BigNumberish>,
      _size: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber[], number[], boolean[], BigNumber]>;
  };

  filters: {
    "AdminTokenRecovery(address,uint256)"(
      token?: null,
      amount?: null
    ): AdminTokenRecoveryEventFilter;
    AdminTokenRecovery(
      token?: null,
      amount?: null
    ): AdminTokenRecoveryEventFilter;

    "LotteryClose(uint256,uint256)"(
      lotteryId?: PromiseOrValue<BigNumberish> | null,
      firstTicketIdNextLottery?: null
    ): LotteryCloseEventFilter;
    LotteryClose(
      lotteryId?: PromiseOrValue<BigNumberish> | null,
      firstTicketIdNextLottery?: null
    ): LotteryCloseEventFilter;

    "LotteryInjection(uint256,uint256)"(
      lotteryId?: PromiseOrValue<BigNumberish> | null,
      injectedAmount?: null
    ): LotteryInjectionEventFilter;
    LotteryInjection(
      lotteryId?: PromiseOrValue<BigNumberish> | null,
      injectedAmount?: null
    ): LotteryInjectionEventFilter;

    "LotteryNumberDrawn(uint256,uint256,uint256)"(
      lotteryId?: PromiseOrValue<BigNumberish> | null,
      finalNumber?: null,
      countWinningTickets?: null
    ): LotteryNumberDrawnEventFilter;
    LotteryNumberDrawn(
      lotteryId?: PromiseOrValue<BigNumberish> | null,
      finalNumber?: null,
      countWinningTickets?: null
    ): LotteryNumberDrawnEventFilter;

    "LotteryOpen(uint256,uint256,uint256,uint256,uint256,uint256)"(
      lotteryId?: PromiseOrValue<BigNumberish> | null,
      startTime?: null,
      endTime?: null,
      priceTicketInBusd?: null,
      firstTicketId?: null,
      injectedAmount?: null
    ): LotteryOpenEventFilter;
    LotteryOpen(
      lotteryId?: PromiseOrValue<BigNumberish> | null,
      startTime?: null,
      endTime?: null,
      priceTicketInBusd?: null,
      firstTicketId?: null,
      injectedAmount?: null
    ): LotteryOpenEventFilter;

    "NewOperatorAndTreasuryAndInjectorAddresses(address,address,address)"(
      operator?: null,
      treasury?: null,
      injector?: null
    ): NewOperatorAndTreasuryAndInjectorAddressesEventFilter;
    NewOperatorAndTreasuryAndInjectorAddresses(
      operator?: null,
      treasury?: null,
      injector?: null
    ): NewOperatorAndTreasuryAndInjectorAddressesEventFilter;

    "NewRandomGenerator(address)"(
      randomGenerator?: PromiseOrValue<string> | null
    ): NewRandomGeneratorEventFilter;
    NewRandomGenerator(
      randomGenerator?: PromiseOrValue<string> | null
    ): NewRandomGeneratorEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "TicketsClaim(address,uint256,uint256,uint256)"(
      claimer?: PromiseOrValue<string> | null,
      amount?: null,
      lotteryId?: PromiseOrValue<BigNumberish> | null,
      numberTickets?: null
    ): TicketsClaimEventFilter;
    TicketsClaim(
      claimer?: PromiseOrValue<string> | null,
      amount?: null,
      lotteryId?: PromiseOrValue<BigNumberish> | null,
      numberTickets?: null
    ): TicketsClaimEventFilter;

    "TicketsPurchase(address,uint256,uint256)"(
      buyer?: PromiseOrValue<string> | null,
      lotteryId?: PromiseOrValue<BigNumberish> | null,
      numberTickets?: null
    ): TicketsPurchaseEventFilter;
    TicketsPurchase(
      buyer?: PromiseOrValue<string> | null,
      lotteryId?: PromiseOrValue<BigNumberish> | null,
      numberTickets?: null
    ): TicketsPurchaseEventFilter;
  };

  estimateGas: {
    MAX_LENGTH_LOTTERY(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_TREASURY_FEE(overrides?: CallOverrides): Promise<BigNumber>;

    MIN_DISCOUNT_DIVISOR(overrides?: CallOverrides): Promise<BigNumber>;

    MIN_LENGTH_LOTTERY(overrides?: CallOverrides): Promise<BigNumber>;

    busdToken(overrides?: CallOverrides): Promise<BigNumber>;

    buyTickets(
      _lotteryId: PromiseOrValue<BigNumberish>,
      _ticketNumbers: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    calculateTotalPriceForBulkTickets(
      _discountDivisor: PromiseOrValue<BigNumberish>,
      _priceTicket: PromiseOrValue<BigNumberish>,
      _numberTickets: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    changeRandomGenerator(
      _randomGeneratorAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    claimTickets(
      _lotteryId: PromiseOrValue<BigNumberish>,
      _ticketIds: PromiseOrValue<BigNumberish>[],
      _brackets: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    closeLottery(
      _lotteryId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    currentLotteryId(overrides?: CallOverrides): Promise<BigNumber>;

    currentTicketId(overrides?: CallOverrides): Promise<BigNumber>;

    drawFinalNumberAndMakeLotteryClaimable(
      _lotteryId: PromiseOrValue<BigNumberish>,
      _autoInjection: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    freeToken(overrides?: CallOverrides): Promise<BigNumber>;

    injectFunds(
      _lotteryId: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    injectorAddress(overrides?: CallOverrides): Promise<BigNumber>;

    manager(overrides?: CallOverrides): Promise<BigNumber>;

    maxNumberTicketsPerBuyOrClaim(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    maxPriceTicketInBusd(overrides?: CallOverrides): Promise<BigNumber>;

    minPriceTicketInBusd(overrides?: CallOverrides): Promise<BigNumber>;

    operatorAddress(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pendingAmountToWinners(overrides?: CallOverrides): Promise<BigNumber>;

    pendingInjectionNextLottery(overrides?: CallOverrides): Promise<BigNumber>;

    randomGenerator(overrides?: CallOverrides): Promise<BigNumber>;

    recoverWrongTokens(
      _tokenAddress: PromiseOrValue<string>,
      _tokenAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setMaxNumberTicketsPerBuy(
      _maxNumberTicketsPerBuy: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setMinAndMaxTicketPriceInBusd(
      _minPriceTicketInBusd: PromiseOrValue<BigNumberish>,
      _maxPriceTicketInBusd: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setOperatorAndTreasuryAndInjectorAddresses(
      _operatorAddress: PromiseOrValue<string>,
      _treasuryAddress: PromiseOrValue<string>,
      _injectorAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    startLottery(
      _endTime: PromiseOrValue<BigNumberish>,
      _priceTicketInBusd: PromiseOrValue<BigNumberish>,
      _discountDivisor: PromiseOrValue<BigNumberish>,
      _rewardsBreakdown: PromiseOrValue<BigNumberish>[],
      _treasuryFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    treasuryAddress(overrides?: CallOverrides): Promise<BigNumber>;

    viewCurrentLotteryId(overrides?: CallOverrides): Promise<BigNumber>;

    viewLottery(
      _lotteryId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    viewNumbersAndStatusesForTicketIds(
      _ticketIds: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    viewRewardsForTicketId(
      _lotteryId: PromiseOrValue<BigNumberish>,
      _ticketId: PromiseOrValue<BigNumberish>,
      _bracket: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    viewUserInfoForLotteryId(
      _user: PromiseOrValue<string>,
      _lotteryId: PromiseOrValue<BigNumberish>,
      _cursor: PromiseOrValue<BigNumberish>,
      _size: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    MAX_LENGTH_LOTTERY(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    MAX_TREASURY_FEE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MIN_DISCOUNT_DIVISOR(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    MIN_LENGTH_LOTTERY(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    busdToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    buyTickets(
      _lotteryId: PromiseOrValue<BigNumberish>,
      _ticketNumbers: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    calculateTotalPriceForBulkTickets(
      _discountDivisor: PromiseOrValue<BigNumberish>,
      _priceTicket: PromiseOrValue<BigNumberish>,
      _numberTickets: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    changeRandomGenerator(
      _randomGeneratorAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    claimTickets(
      _lotteryId: PromiseOrValue<BigNumberish>,
      _ticketIds: PromiseOrValue<BigNumberish>[],
      _brackets: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    closeLottery(
      _lotteryId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    currentLotteryId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    currentTicketId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    drawFinalNumberAndMakeLotteryClaimable(
      _lotteryId: PromiseOrValue<BigNumberish>,
      _autoInjection: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    freeToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    injectFunds(
      _lotteryId: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    injectorAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    manager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    maxNumberTicketsPerBuyOrClaim(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maxPriceTicketInBusd(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    minPriceTicketInBusd(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    operatorAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pendingAmountToWinners(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pendingInjectionNextLottery(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    randomGenerator(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    recoverWrongTokens(
      _tokenAddress: PromiseOrValue<string>,
      _tokenAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setMaxNumberTicketsPerBuy(
      _maxNumberTicketsPerBuy: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setMinAndMaxTicketPriceInBusd(
      _minPriceTicketInBusd: PromiseOrValue<BigNumberish>,
      _maxPriceTicketInBusd: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setOperatorAndTreasuryAndInjectorAddresses(
      _operatorAddress: PromiseOrValue<string>,
      _treasuryAddress: PromiseOrValue<string>,
      _injectorAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    startLottery(
      _endTime: PromiseOrValue<BigNumberish>,
      _priceTicketInBusd: PromiseOrValue<BigNumberish>,
      _discountDivisor: PromiseOrValue<BigNumberish>,
      _rewardsBreakdown: PromiseOrValue<BigNumberish>[],
      _treasuryFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    treasuryAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    viewCurrentLotteryId(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    viewLottery(
      _lotteryId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    viewNumbersAndStatusesForTicketIds(
      _ticketIds: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    viewRewardsForTicketId(
      _lotteryId: PromiseOrValue<BigNumberish>,
      _ticketId: PromiseOrValue<BigNumberish>,
      _bracket: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    viewUserInfoForLotteryId(
      _user: PromiseOrValue<string>,
      _lotteryId: PromiseOrValue<BigNumberish>,
      _cursor: PromiseOrValue<BigNumberish>,
      _size: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
